apiVersion: v1
kind: Service
metadata:
  name: mkdocs
  labels:
    app: mkdocs
spec:
  selector:
    app: mkdocs
  type: NodePort  # Changed to LoadBalancer for cloud environments
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30081  # Access via localhost:30081
      protocol: TCP
